name: ci

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    strategy:
      fail-fast: false
      matrix:
        go: [1.16.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build and release gr
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install macOS prerequisites
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install coreutils make upx
      - name: Install Ubuntu prerequisites
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install make upx-ucl
      - name: Install Windows prerequisites
        if: ${{ matrix.os == 'windows-latest' }}
        run: choco install make upx
      - name: Build gr
        run: make
      - name: Release gr
        uses: softprops/action-gh-release@v1
        with:
          files: out/gr_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
